service: auth-typescript

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
    


package:
  excludeDevDependencies: true

custom:
  bundle:
    linting: false
